'use client'

import Link from 'next/link'
import { useMemo, useState } from 'react'
import { EmptyState } from '@/components/shared/data-state'
import type { Resource, ResourceStatus } from '@/types/resource'

const statusLabels: Record<ResourceStatus, string> = { available: 'Available', reserved: 'Reserved', checked_out: 'Checked out', maintenance: 'Maintenance', unavailable: 'Unavailable', retired: 'Retired' }

export function ResourceList({ resources, canManageResources }: { resources: Resource[]; canManageResources: boolean }) {
  const [query, setQuery] = useState(''); const [status, setStatus] = useState<'all' | ResourceStatus>('all'); const [category, setCategory] = useState('all'); const [location, setLocation] = useState('all'); const [availability, setAvailability] = useState<'all' | 'available' | 'unavailable'>('all')
  const categories = useMemo(() => [...new Set(resources.map(resource => resource.category))].sort(), [resources]); const locations = useMemo(() => [...new Set(resources.map(resource => resource.location))].sort(), [resources])
  const filtered = useMemo(() => resources.filter(resource => { const matchesQuery = (resource.name + ' ' + resource.category + ' ' + resource.location + ' ' + (resource.assetCode ?? '')).toLowerCase().includes(query.trim().toLowerCase()); const isAvailable = resource.status === 'available' && resource.availableQuantity > 0; return matchesQuery && (status === 'all' || resource.status === status) && (category === 'all' || resource.category === category) && (location === 'all' || resource.location === location) && (availability === 'all' || (availability === 'available' ? isAvailable : !isAvailable)) }), [resources, query, status, category, location, availability])
  const clearFilters = () => { setQuery(''); setStatus('all'); setCategory('all'); setLocation('all'); setAvailability('all') }

  return <>
    <div className="resource-toolbar resource-filters"><label className="sr-only" htmlFor="resource-search">Search resources</label><input id="resource-search" value={query} onChange={event => setQuery(event.target.value)} placeholder="Search resources..." /><label className="sr-only" htmlFor="resource-category">Filter by category</label><select id="resource-category" value={category} onChange={event => setCategory(event.target.value)}><option value="all">All categories</option>{categories.map(value => <option key={value} value={value}>{value}</option>)}</select><label className="sr-only" htmlFor="resource-location">Filter by location</label><select id="resource-location" value={location} onChange={event => setLocation(event.target.value)}><option value="all">All locations</option>{locations.map(value => <option key={value} value={value}>{value}</option>)}</select><label className="sr-only" htmlFor="resource-availability">Filter by availability</label><select id="resource-availability" value={availability} onChange={event => setAvailability(event.target.value as typeof availability)}><option value="all">Any availability</option><option value="available">Available now</option><option value="unavailable">Unavailable</option></select><label className="sr-only" htmlFor="resource-status">Filter by status</label><select id="resource-status" value={status} onChange={event => setStatus(event.target.value as 'all' | ResourceStatus)}><option value="all">All statuses</option>{Object.entries(statusLabels).filter(([value]) => value !== 'retired').map(([value, text]) => <option key={value} value={value}>{text}</option>)}</select>{canManageResources && <Link className="primary-button" href="/resources/new">Add resource</Link>}</div>
    <p className="sr-only" aria-live="polite">{filtered.length} resource{filtered.length === 1 ? '' : 's'} shown</p>
    {filtered.length === 0 ? <EmptyState title="No resources found" description="Try a different search or filter." action={<button type="button" className="text-button" onClick={clearFilters}>Clear filters</button>} /> : <div className="resource-list">{filtered.map(resource => <Link className="resource-row" href={'/resources/' + resource.id} key={resource.id}><div><strong>{resource.name}</strong><span>{resource.assetCode ?? 'No asset code'} · {resource.location}</span></div><div><span>{resource.category}</span><span role="status" className={'resource-status ' + resource.status}>{statusLabels[resource.status]}</span></div><div>{resource.availableQuantity} / {resource.quantity} available</div></Link>)}</div>}
  </>
}
